Custom background image
FAForever/downlords-faf-client pull request #1089
Opened 2019-01-05 14:48 UTC by 20seven

Adds setting to define custom background image saved locally
Fixes #1059

2019-01-05 14:52 UTC, 20seven commented on src/main/resources/theme/style.css
>  }
Was hesitating if I should have removed the entire class, as well as from styleClass="main-window" in the fxml. I guess I should?

2019-01-07 17:51 UTC, 1-alex98 submitted a review, later dismissed

2019-02-02 15:28 UTC, micheljung requested changes

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/main/MainController.java
> +    setBackgroundImage(preferencesService.getPreferences().getMainWindow().backgroundImagePathProperty().getValue());
```suggestion
    setBackgroundImage(preferencesService.getPreferences().getMainWindow().getBackgroundImagePath());
```

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/main/MainController.java
> +      setBackgroundImage(mainWindowPrefs.backgroundImagePathProperty().getValue());
```suggestion
      setBackgroundImage(mainWindowPrefs.getBackgroundImagePath());
```

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/main/MainController.java
> +  private void setBackgroundImage(String filepath) {
```suggestion
  private void setBackgroundImage(Path filepath) {
```

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/main/MainController.java
> +      File file = new File(filepath);
`java.io.File` is pre-Java 7 and should be avoided, instead use `java.nio.file.Path`

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/preferences/WindowPrefs.java
> +  private final StringProperty backgroundImagePath;
```suggestion
  private final ObjectProperty<Path> backgroundImagePath;
```

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/preferences/WindowPrefs.java
> +    backgroundImagePath = new SimpleStringProperty();
```suggestion
    backgroundImagePath = new SimpleObjectProperty<>();
```

2019-02-02 15:28 UTC, micheljung commented on src/main/java/com/faforever/client/preferences/ui/SettingsController.java
> +      preferencesService.getPreferences().getMainWindow().setBackgroundImagePath(result.getPath());
```suggestion
      preferencesService.getPreferences().getMainWindow().setBackgroundImagePath(result.toPath());
```

2019-02-02 15:28 UTC, micheljung commented on src/main/resources/theme/style.css
>  }
It's fine if you keep it in the FXML, allows theme creators to modify it. In CSS, you can remove it.

2019-02-27 18:26 UTC, 1-alex98 submitted a review, later dismissed

2019-03-20 20:29 UTC, merged