Workaround to avoid native crash
FAForever/downlords-faf-client pull request #1133
Opened 2019-03-21 18:42 UTC by axel1200

Fixes #1080

2019-03-25 17:18 UTC, micheljung requested changes
Something's wrong with the changes in this PR

2019-03-26 11:47 UTC, axel1200 commented
@micheljung i rebased onto reinitiate-conectivity code to be able to build a test release? But forgot to close PR or make a different version for PR... I am waiting for the feedback of @tomaskir

2019-03-26 11:48 UTC, axel1200 commented on src/main/java/com/faforever/client/chat/ChannelTabController.java
> +    Platform.runLater(() -> engine.executeScript("removeUserMessageClass(\'" + String.format(USER_CSS_CLASS_FORMAT, chatUser.getUsername()) + "\',\'" + cssClass + "\');"));
Only line that changed

2019-06-11 10:01 UTC, axel1200 commented
Downlords update of the version did not succeed

2019-06-11 19:21 UTC, Brutus5000 approved these changes

2019-06-11 19:22 UTC, merged