Dont throw exception but display unknown mission
FAForever/downlords-faf-client pull request #1148
Opened 2019-04-19 16:03 UTC by axel1200

Prepares #1134

2019-04-24 19:13 UTC, Brutus5000 requested changes

2019-04-24 19:13 UTC, Brutus5000 commented on src/main/resources/i18n/messages.properties
> +coop.unknownMission=unknown mission
I'd start with an uppercase letter like in 99% of all other messages.

2019-04-24 19:13 UTC, Brutus5000 commented on src/main/java/com/faforever/client/coop/CoopController.java
> +        Function<String, String> coopMissionNameProvider = (mapFolderName -> {
It's too big now. We should put it into a new function imho.

2019-04-26 17:05 UTC, axel1200 commented
Please somebody review

2019-04-26 17:10 UTC, axel1200 commented
@Geosearchef would u mind reviewing?

2019-05-02 19:03 UTC, micheljung approved these changes

2019-05-02 19:05 UTC, merged