Ask user if to reset settings
FAForever/downlords-faf-client pull request #1172
Opened 2019-04-27 18:07 UTC by axel1200

Fixes 1171

2019-04-27 18:08 UTC, axel1200 commented on src/main/java/com/faforever/client/preferences/PreferencesService.java
> +        Alert errorReading = new Alert(AlertType.ERROR, "Error reading setting. Reset settings? ", ButtonType.YES, ButtonType.CANCEL);
Notification service and internationalization are not loaded so we use those default error pop ups

2019-05-02 19:13 UTC, micheljung requested changes

2019-05-02 19:13 UTC, micheljung commented on src/main/java/com/faforever/client/theme/UiService.java
> +        logger.warn("Missing permission to delete style sheets cache directory ''{}''", cacheStylesheetsDirectory);
Double single quotes not needed

2019-05-02 19:13 UTC, micheljung commented on src/main/java/com/faforever/client/preferences/PreferencesService.java
> +            Alert errorDeleting = new Alert(AlertType.ERROR, "Error deleting setting. Please delete them yourself. You find them under C:\\Users\\[username]\\AppData\\Roaming\\Forged Alliance Forever
Don't hardcode this path; use `preferencesFilePath.toAbsolutePath()`

2019-05-03 22:07 UTC, merged