Bugfix/#1164 coop replay broken
FAForever/downlords-faf-client pull request #1185
Opened 2019-05-04 08:19 UTC by CyrilPaulus

This fix allow to correctly play coop replays.
I don't know if it's the right solution thought .

For some reason for the coop replays the map file name is empty in the metadata.
Maybe we should fix the replay files instead ?

2019-05-04 22:47 UTC, 1-alex98 requested changes

2019-05-04 22:47 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +  private void runFafReplayFile(Path path, String overrideMapName) throws IOException {
Please tell me why is that needed and please make a some java doc /comment on it because it does not seem very obvious

2019-05-04 22:50 UTC, axel1200 commented
Please try to always put one issue into one commit via amend option. And if you format the comitt the following way
[title]
[newline]
[description]
Fixes #[issue number]

Then github closes the issue on merge and also puts the title as title and the description as description in the PR by itself

2019-05-05 07:42 UTC, CyrilPaulus commented
Ok noted.

I found another cleaner way to fix the problem.

I'll close this pull request and open another cleaner one with the correct commit naming convention and one commit per issue.

2019-05-05 07:42 UTC, closed without merging