Fixes # 963 Added space for drag bar
FAForever/downlords-faf-client pull request #1248
Opened 2019-05-15 21:51 UTC by johnhce

Added space for drag bar at top of main window.

2019-05-16 20:24 UTC, 1-alex98 requested changes

2019-05-16 20:24 UTC, axel1200 commented on src/main/resources/theme/main.fxml
> +	            </HBox>
Please format correctly

2019-05-17 20:30 UTC, 1-alex98 approved these changes

2019-05-18 17:48 UTC, axel1200 commented on src/main/resources/theme/main.fxml
> +	            </HBox>
Use Intelij and turn on auto formatting ;)

2019-05-20 19:12 UTC, merged

2019-05-20 19:16 UTC, axel1200 commented
Please dont use a fork but make branches in the main project so we can checkout and test more easily

2019-05-20 19:17 UTC, micheljung commented
Why add two additional nodes with a hardcoded size when the same (read: better) could be achieved using simple CSS?

2019-05-20 19:19 UTC, axel1200 commented
only minheight is hardcoded tho

2019-05-20 19:21 UTC, axel1200 commented
You want a padding at the top?

2019-05-20 19:23 UTC, micheljung commented
Plus, the commit message says "Fixes # 963" which, due to the space after the hash, does not close #963.
Plus, my comment in https://github.com/FAForever/downlords-faf-client/issues/963 seems to have been ignored, so now there's also spacing when the window is maximized, which is bad for usability.

Please revert this, and please pay more attention to quality (I'm not even mentioning the 7 ghost-commits in this PR).

2019-05-20 19:45 UTC, axel1200 commented
Reverted

2019-05-20 19:46 UTC, axel1200 commented
I squased the commits but also told him 1 issue = 1 commit