Fix isAdmin() breaking if cmd.exe has no output
FAForever/downlords-faf-client pull request #1257
Opened 2019-05-20 19:35 UTC by Wesmania

Fixes #1255.

Signed-off-by: Igor Kotrasinski <i.kotrasinsk@gmail.com>

2019-05-20 19:40 UTC, axel1200 commented
What about a catch Exception in genral to avoid any unexpected behaviours ?

2019-05-20 19:40 UTC, axel1200 commented
Have a look at Codacy and what it complain about

2019-05-20 19:41 UTC, 1-alex98 requested changes

2019-05-20 19:41 UTC, axel1200 commented on src/main/java/com/faforever/client/util/WindowsUtil.java
> +        if (!scanner.hasNextLine())     /* Unexpected output, bail out */
use bracets

2019-05-20 19:41 UTC, 1-alex98 requested changes

2019-05-20 19:41 UTC, axel1200 commented on src/main/java/com/faforever/client/util/WindowsUtil.java
> +        if (!scanner.hasNextLine())     /* Unexpected output, bail out */
and remove comment

2019-05-22 15:03 UTC, Wesmania commented on src/main/java/com/faforever/client/util/WindowsUtil.java
> +        if (!scanner.hasNextLine())     /* Unexpected output, bail out */
Bureaucracy :/

2019-05-26 19:12 UTC, 1-alex98 approved these changes

2019-05-26 23:55 UTC, Brutus5000 approved these changes

2019-05-27 07:37 UTC, merged

2019-06-28 23:18 UTC, norraxx commented
why not
```
while(scanner.hasNextLine()) {
```
?

2019-06-29 08:06 UTC, axel1200 commented
Because we are only interested in the first one...