Make separate list for sortable properties
FAForever/downlords-faf-client pull request #1270
Opened 2019-05-26 21:44 UTC by axel1200

Fixes #1263

2019-05-26 21:44 UTC, axel1200 commented
Needs 1 or 2 things cleaned up

2019-05-29 11:00 UTC, Brutus5000 requested changes
Some properties should not be sortable to reduce the list to a more user friendly size:
- descriptions
- mod/map version (we only show the latest anyway)
- folderName
- updatedTime
- mod uid

2019-05-29 11:00 UTC, Brutus5000 commented on src/main/java/com/faforever/client/query/SortableProperties.java
> +public class SortableProperties {
The defined constants are obviously not properties but key mappings since Property is a dedicated class now. (Applies for all 3)

2019-06-03 18:28 UTC, axel1200 commented on src/main/java/com/faforever/client/query/SortableProperties.java
> +public class SortableProperties {
You want me to rename constants?

2019-06-07 19:33 UTC, Brutus5000 approved these changes

2019-06-07 19:34 UTC, merged