If steam game is installed use it
FAForever/downlords-faf-client pull request #1286
Opened 2019-06-10 21:34 UTC by axel1200

Fix #1285

2019-06-10 21:40 UTC, Geosearchef approved these changes

2019-06-11 16:28 UTC, Brutus5000 requested changes
path is deprecated but installationPath seems to be used almost nowhere.
I sense code smell here.
Can you please validate?

2019-06-11 17:23 UTC, axel1200 commented
Ok yeah i also noticed that however installationPath is never used anywhere....

2019-06-14 19:34 UTC, Brutus5000 approved these changes

2019-06-14 19:47 UTC, merged