Add tooltip to GameTabelController
FAForever/downlords-faf-client pull request #1339
Opened 2019-07-03 02:06 UTC by Katharsas

Same tooltip controller as used in GameTileController.
Fixes #1338

May need some help with tests if those are wanted and even possible to test.

2019-07-03 16:25 UTC, axel1200 commented
Can u post a screen shot so I can imagine what u are doing here?

2019-07-03 16:55 UTC, Katharsas commented
![coop_tooltip](https://user-images.githubusercontent.com/1922573/60610424-1f8d1000-9dc4-11e9-8f84-8198853465da.JPG)

2019-07-03 16:57 UTC, axel1200 commented
This is now also the case in the table of normal games right....

2019-07-03 16:57 UTC, axel1200 commented
I am on discord and we can try to figure out how to test it...

2019-07-03 16:57 UTC, Katharsas commented
yeah thats what i meant.

2019-07-03 22:12 UTC, Brutus5000 reviewed
I'm not convinced by this change yet. Why do we need to reload the tooltip every time from the fxml? I guess this is pretty expensive. Why not store one loaded controller and just update the displayed game?

2019-07-03 23:35 UTC, axel1200 commented
We fixed this along with many other things concerning the tool tip a second ago

2019-07-04 21:26 UTC, 1-alex98 requested changes

2019-07-04 21:26 UTC, axel1200 commented on src/main/java/com/faforever/client/game/GamesTableController.java
> +
?

2019-07-04 21:26 UTC, axel1200 commented on src/test/java/com/faforever/client/game/GamesTableControllerTest.java
> +    Platform.runLater(() -> {
Use WaitForAsyncUtils.executeAsyncFX something

2019-07-04 21:27 UTC, axel1200 commented on src/test/java/com/faforever/client/game/GamesTableControllerTest.java
> +    Platform.runLater(() -> {
and then get()

2019-07-12 23:08 UTC, Brutus5000 commented
Looks better to me now, but I'm not deep into the JavaFX stuff to actually approve this. It's up to @axel1200 now.

2019-07-13 09:21 UTC, 1-alex98 approved these changes

2019-07-13 09:23 UTC, merged