Fix circular dependency ReplayService <-> GameService
FAForever/downlords-faf-client pull request #1397
Opened 2019-08-18 23:52 UTC by Katharsas

Split ReplayService:
- `ReplayFileService` for the important stuff that has to do with handling replay files and starting replays
- `ReplayRemoteService`; i really don't know why these methods even need to exist if they just wrap `ReplayServer` and `FafService` but ok

Fixes #1396

2019-08-19 00:37 UTC, Katharsas commented
Ok seems like the client doesnt even start locally now.

2019-08-19 01:44 UTC, Katharsas commented
Ok so now there is still a circular dependency between `GameService` and `ReplayServer`.

2019-08-19 01:54 UTC, Katharsas commented
Btw since i removed member injection the circular dependency will now cause every startup to fail, including local ones, so anybody can reproduce.

2019-08-28 01:35 UTC, Katharsas commented
Thinking about renaming `ReplayFileService` back to `ReplayService` to keep git history more readable and prevent a bunch of variable renaming otherwise needed. Opinions?

The ReplayServer circle can be resolved by passing game supplier function to replayService instead of replayService querying gameService. Opinions?

2019-08-28 09:26 UTC, axel1200 commented
> First circular dependency (solved):
> Thinking about renaming `ReplayFileService` back to `ReplayService` to keep git history more readable and prevent a bunch of variable renaming otherwise needed. Opinions?
> 
> Second circular dependency:
> The ReplayServer circle can be resolved by passing game supplier function to ReplayServer instead of ReplayServer querying GameService. Not pretty but i don't see alternatives since it is called from a separate thread inside ReplayServer which makes other solutions not pretty as well. Opinions?
> 
> Once ReplayServer is changed, this issue is solved and client installer can be built (see branch `hotfix/homepage-download`, where i implemented above suggestion).

You will need to explain that to me maybe discord?

2019-08-29 08:56 UTC, 1-alex98 approved these changes

2019-08-29 08:58 UTC, 1-alex98 requested changes

2019-08-29 08:58 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayServerImpl.java
> +    // game needs to running or finished
Remove

2019-08-29 13:24 UTC, axel1200 commented
build it and tested it

2019-08-29 13:25 UTC, 1-alex98 approved these changes

2019-08-29 13:26 UTC, merged