Fix missing uninstall calls for tooltips
FAForever/downlords-faf-client pull request #1423
Opened 2019-09-04 21:02 UTC by Katharsas

Fixes #1421

2019-09-04 21:41 UTC, axel1200 commented
Lets see if that was it but I can imagine so. There where lots of tooltips in memory dump

2019-09-05 14:46 UTC, Brutus5000 requested changes

2019-09-05 14:46 UTC, Brutus5000 commented on src/main/java/com/faforever/client/game/GamesTilesContainerController.java
> +            boolean remove = tiledFlowPane.getChildren().remove(card);
The following three lines should go into the card!=null block
The else block should also throw an error in the log.
(We don't know how many times it actually occurs and that would help I guess)

2019-09-05 19:27 UTC, Brutus5000 approved these changes

2019-09-06 15:39 UTC, 1-alex98 approved these changes

2019-09-06 15:40 UTC, axel1200 commented
@Katharsas did you check if tooltips are removed in chat as well?

2019-09-06 15:43 UTC, axel1200 commented
I think the tooltips are never removed but i think the difference is that the tooltip is not held by an external Controller

2019-09-06 15:43 UTC, axel1200 commented
So should be fine

2019-09-06 18:54 UTC, Katharsas commented
We basically made a search for `*.install` in all sources and made sure that every install has corresponding uninstall. Don't remember if we found chat stuff.

2019-09-06 19:39 UTC, merged