Tooltip memory leak fix
FAForever/downlords-faf-client pull request #1463
Opened 2019-10-12 16:48 UTC by Katharsas

Fixes #1462

2019-10-12 21:18 UTC, 1-alex98 requested changes

2019-10-12 21:18 UTC, 1-alex98 commented on src/main/java/com/faforever/client/fx/JavaFxUtil.java
> +    PopupWindowHelper.getContent(tooltip).setAll(content);// effectively calls tooltip.getContent.setAll()
remove

2019-10-12 22:00 UTC, 1-alex98 approved these changes

2019-10-13 20:32 UTC, Brutus5000 approved these changes

2019-10-13 20:32 UTC, 1-alex98 approved these changes

2019-10-13 20:34 UTC, merged