Don't omit coop maps from the local map list
FAForever/downlords-faf-client pull request #1561
Opened 2020-01-19 19:53 UTC by andreasley

Fixes #1560.

Previously, only skirmish maps were added to the list of installed maps. This led to replays of coop missions not showing up.
This patch fixes this while retaining the filter for skirmish maps when creating a new game.

2020-01-20 13:19 UTC, Geosearchef submitted a review, later dismissed
Looks good to me, are you sure installedMaps and mapsByName are kept im sync correctly?

2020-01-20 13:19 UTC, Geosearchef commented on src/main/java/com/faforever/client/map/MapService.java
> +      return Optional.of(mapBean);
I'd either remove the else, therefore having it as an abort condition or swap if and else around.

2020-01-20 16:12 UTC, bukajsytlos commented
or return Optional.ofNullable(map. getValue(key))

On Mon, 20 Jan 2020, 14:19 Geosearchef, <notifications@github.com> wrote:

> *@Geosearchef* approved this pull request.
>
> Looks good to me, are you sure installedMaps and mapsByName are kept im
> sync correctly?
> ------------------------------
>
> In src/main/java/com/faforever/client/map/MapService.java
> <https://github.com/FAForever/downlords-faf-client/pull/1561#discussion_r368542373>
> :
>
> >    public Optional<MapBean> getMapLocallyFromName(String mapFolderName) {
>      logger.debug("Trying to find map '{}' locally", mapFolderName);
> -    ObservableList<MapBean> installedMaps = getInstalledMaps();
> -    synchronized (installedMaps) {
> -      for (MapBean mapBean : installedMaps) {
> -        if (mapFolderName.equalsIgnoreCase(mapBean.getFolderName())) {
> -          logger.debug("Found map {} locally", mapFolderName);
> -          return Optional.of(mapBean);
> -        }
> -      }
> +    String mapFolderKey = mapFolderName.toLowerCase();
> +    if (!mapsByFolderName.containsKey(mapFolderKey)) {
> +      return Optional.empty();
> +    } else {
> +      MapBean mapBean = mapsByFolderName.get(mapFolderKey);
> +      return Optional.of(mapBean);
>
> I'd either remove the else, therefore having it as an abort condition or
> swap if and else around.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FAForever/downlords-faf-client/pull/1561?email_source=notifications&email_token=ACBYJJP2SL5EKMYIM75V56LQ6WQFPA5CNFSM4KI3F7T2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCSKN6VY#pullrequestreview-345300823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBYJJKGFH7ZE62K5WRUGTLQ6WQFPANCNFSM4KI3F7TQ>
> .
>

2020-01-21 17:41 UTC, andreasley commented
> Looks good to me, are you sure installedMaps and mapsByName are kept im sync correctly?

Reasonably sure, as there's a change listener on `installedMaps` that updates `mapsByName`.

2020-02-08 22:46 UTC, 1-alex98 requested changes
What about the maps shon in the create game dialog do they now contain coop maps!!???

2020-02-09 07:40 UTC, andreasley commented
> What about the maps shon in the create game dialog do they now contain coop maps!!???

No, of course not. :)

2020-02-09 17:44 UTC, axel1200 commented
True found the code for that

2020-02-09 17:45 UTC, 1-alex98 approved these changes

2020-02-10 17:55 UTC, axel1200 commented
tested it look good

2020-02-10 17:56 UTC, merged