Fixes #1562
FAForever/downlords-faf-client pull request #1573
Opened 2020-02-09 00:02 UTC by axel1200

2020-02-10 19:20 UTC, Geosearchef requested changes

2020-02-10 19:20 UTC, Geosearchef commented on src/main/java/com/faforever/client/game/GamesTableController.java
> +  public void initializeGameTable(ObservableList<Game> games, Function<String, String> coopMissionNameProvider, Boolean listenToFilterPreferences) {
use primitive boolean

2020-02-14 11:48 UTC, Brutus5000 submitted a review, later dismissed
Apart from Geosearchefs suggestion, looks good.

2020-02-18 20:26 UTC, Katharsas commented
Ok so the reason to keep the columns in the coop table at all times is that you cannot see the filter settings and therefore its nice to have the columns always?

If thats the case i would rename the boolean flagh to `hideColumnsForFilteredAttributes` or something but looks fine otherwise.

2020-02-19 11:03 UTC, axel1200 commented
Yes

2020-02-19 11:20 UTC, Katharsas submitted a review, later dismissed
Ok.

2020-02-26 00:54 UTC, merged