Add game type description
FAForever/downlords-faf-client pull request #1795
Opened 2020-06-21 10:40 UTC by QTimort

Pull request that address https://github.com/FAForever/downlords-faf-client/issues/1612
![image](https://user-images.githubusercontent.com/25301692/85222545-428d4700-b3bc-11ea-86f4-46a9da4f4f81.png)

2020-06-21 12:09 UTC, 1-alex98 requested changes

2020-06-21 12:09 UTC, axel1200 commented on src/main/java/com/faforever/client/fx/DualStringListCellController.java
> +    uiService.registerWebView(web);
u need to do a null check on apply... also u need to remove the tooltip on null because the controller might be reused

2020-06-21 12:09 UTC, axel1200 commented on src/main/java/com/faforever/client/fx/DualStringListCellController.java
> +    left.setTooltip(tip);
we try to stick to mvc . So it should be done in fxml file. Either in this one for a serpate one. And further DualStringListCellController is a Class that is potentially used else where as well adding this pretty sepecific behaviour here seems strange, especially when the method is called setLeftTextTooltip, where it is rather addTooltipWithWebview. So yes u might add this webview capabilities here but make sue your naming reflects that it is not a normal tooltip. Also try define Webview and maybe even tooltip in fxml. On the other hand if it is hard to define in FXML I guess we can leave it tho. Further 3 seconds seem to be short. And dividing the pref size by half is also strange. Why do u do it? Maybe just hard code it :D Could even make use units dpending on screen size.

2020-06-21 12:10 UTC, axel1200 commented
And unit test 🤔

2020-06-21 12:10 UTC, axel1200 commented
But nice job. Are u on Zulip? Do you want to be invited?

2020-06-21 12:11 UTC, QTimort commented
> But nice job. Are u on Zulip? Do you want to be invited?

Yes I'm Zulip (Timort)

2020-06-24 15:42 UTC, micheljung commented
Thanks for contributing! Please make sure to follow [The seven rules of a great Git commit message](http://chris.beams.io/posts/git-commit/#seven-rules).

2020-07-31 18:18 UTC, Askaholic commented
Any progress on this?

2020-08-04 17:56 UTC, QTimort commented
Hello, no progress so far, I'm quite busy those days, so if someone wants to take this over he can, otherwise I'll get back to it in like 1 - 2 months max

2020-08-29 19:58 UTC, Sheikah45 commented
@axel1200 I am going to make the changes for this but wanted to know why the featuredmod list uses the dual string cell list in the first place as it seems it only uses the left

2020-08-29 20:48 UTC, Sheikah45 commented
Refactored to use the fxml files currently uses the dual list cell. However if this is an issue we can change it.

2020-08-30 11:48 UTC, axel1200 commented
Also needs to be rebased on new design right?

2020-08-30 11:52 UTC, Sheikah45 commented
I believe I rebased it when I committed although some css might need to be updated to look nice

2020-09-07 21:04 UTC, axel1200 commented
Remember me to rebase and test it :D

2020-09-18 03:02 UTC, Sheikah45 commented
rebased

2020-09-20 09:44 UTC, axel1200 approved these changes
Nomands text is black, do you know why

2020-09-20 09:45 UTC, axel1200 commented on src/main/resources/theme/dual_string_list_cell.fxml
> +            <Tooltip contentDisplay="GRAPHIC_ONLY" showDelay=".5s" hideDelay="2s" showDuration="30s">
Made it show 30 seconds so u can actually read the text

2020-09-20 11:07 UTC, Sheikah45 commented
The text color is defined in the html that we receive for the description and for some reason in nomads they set the color to black

2020-09-20 15:42 UTC, axel1200 commented
Well then so be it

2020-09-20 15:56 UTC, Sheikah45 commented
Yeah so wherever the html is retrieved from needs to be changed

2020-09-20 15:59 UTC, axel1200 commented
database @Brutus5000 @betrok need to do it

2020-10-11 20:14 UTC, merged