Create game title text field changes background to red if not filled out
FAForever/downlords-faf-client pull request #1819
Opened 2020-07-09 21:26 UTC by TobiasJacob

Fixes #1813 

I'm new in FAF development, so I hope the implementation is ok. It changes the background color of the title text-field of the create game page to red to attract more attention if it's empty.

2020-07-10 09:31 UTC, micheljung commented
Hi Tobias and thanks for contributing! I'll review your PR

2020-07-10 09:36 UTC, micheljung requested changes

2020-07-10 09:36 UTC, micheljung commented on src/main/java/com/faforever/client/game/CreateGameController.java
> +  }
We try to avoid hardcoding any styles. So basically, we never call `setStyle()`. Instead, have a look at `titleTextField.pseudoClassStateChanged()`.

Assuming we call the pseudo class `invalid`, it can then be styled like so:

```css
.game-title-input:invalid {
  -fx-background-color: -bad;
}
```

... even though I think that a red background will look nasty :-) So I'd rather go with `-fx-border-color: -bad`

2020-07-10 09:36 UTC, micheljung commented on src/main/resources/theme/style.css
> +  -fx-prompt-text-fill: -fx-light-text-color;
I think this is obsolete then

2020-07-10 09:36 UTC, micheljung commented on src/main/java/com/faforever/client/game/CreateGameController.java
> +      // titleTextField.setBackground(new Background(new BackgroundFill(Paint.valueOf("FF0000"), CornerRadii.EMPTY, Insets.EMPTY)));
Dead code should be removed

2020-07-10 11:51 UTC, TobiasJacob commented
Hello @micheljung, I agree with your suggestions and implemented them

2020-07-11 08:16 UTC, 1-alex98 requested changes

2020-07-11 08:16 UTC, axel1200 commented on src/main/java/com/faforever/client/game/CreateGameController.java
> +    adjustCreateGameButtonBackgroundColor(titleTextField.getText());
Add a unit test set the text to "" and to "test" and see if the Pseudo class is set correctly.

2020-07-11 08:17 UTC, axel1200 commented on src/main/java/com/faforever/client/game/CreateGameController.java
> +    adjustCreateGameButtonBackgroundColor(titleTextField.getText());
Should be easy to test

2020-07-11 11:22 UTC, TobiasJacob commented
Hello @axel1200, I hope this is implemented correctly

2020-07-14 19:22 UTC, 1-alex98 approved these changes

2020-07-17 13:41 UTC, axel1200 commented on src/main/java/com/faforever/client/game/CreateGameController.java
> +  }
Resolving this as this was done

2020-07-17 13:41 UTC, axel1200 commented on src/main/java/com/faforever/client/game/CreateGameController.java
> +    adjustCreateGameButtonBackgroundColor(titleTextField.getText());
Resolving this as this was done

2020-07-17 13:42 UTC, 1-alex98 approved these changes

2020-07-17 13:45 UTC, axel1200 commented
Looks strange but well somebody is someday gonna come up with a prettier way

2020-07-17 13:45 UTC, merged