Feature/#1763 local replays pagination
FAForever/downlords-faf-client pull request #1820
Opened 2020-07-10 08:27 UTC by IAmAlife

Done after unittesting

2020-07-10 10:07 UTC, micheljung commented
It looks like there are many commits in this PR that shouldn't be. Please sort this out first.

2020-07-10 17:39 UTC, axel1200 commented
@micheljung on the other hand I can also squash this on merge

2020-07-10 17:48 UTC, 1-alex98 requested changes
Also misses unit tests

2020-07-10 17:48 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +  public void startLoadingAndWatchingLocalReplays(Pagination pagination) {
Passing on UI Elements to a service should never happen!

2020-07-10 17:48 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +      publisher.publishEvent(new LocalReplaysChangedEvent(this, replays, new ArrayList<>()));
Publish page count here maybe...

2020-07-10 17:48 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +      logger.error("Failed loading total amount of replays", e);
This is not an error, rather warning I say

2020-07-10 17:48 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
>    protected void onLocalReplaysWatchEvent(WatchKey key) {
Have u thought about what happens if a user drops a new replay into his replay folder... that is what happens here.

2020-07-10 17:48 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
>    protected void onLocalReplaysWatchEvent(WatchKey key) {
Maybe u can simplify this method by just going back to the first page :thinking:

2020-07-10 17:51 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +      publisher.publishEvent(new LocalReplaysChangedEvent(this, replays, new ArrayList<>()));
I am surprised this works with an event publisher. Probably the Controller a singleton and that's why it works. Whatever let's leave it like this.

2020-07-12 14:16 UTC, micheljung commented
> @micheljung on the other hand I can also squash this on merge

If you write a proper commit message, sure. But I won't accept the default generated commit message ;-)

2020-07-17 09:26 UTC, 1-alex98 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +  private double localReplaysItemsSize;
whys that a double

2020-07-17 13:40 UTC, 1-alex98 requested changes

2020-07-17 13:40 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +  protected List<Replay> localReplays = new ArrayList<>();
Written to but never read, right? If so remove

2020-07-23 13:28 UTC, 1-alex98 requested changes

2020-07-23 13:28 UTC, axel1200 commented on src/main/java/com/faforever/client/replay/ReplayService.java
> +    try (DirectoryStream<Path> directoryStream = Files.newDirectoryStream(replaysDirectory, replayFileGlob)) {
Files.list

2020-08-29 13:55 UTC, Sheikah45 commented
Did we want to do the local replay pagination this way? I can rebase and bring it up to current.

2020-08-29 15:45 UTC, axel1200 commented
We need to definetely rebase it. How would u do it otherwise?

2020-08-29 21:34 UTC, Sheikah45 commented
I would probably want to refactor it a bit to make it more similar to the other paginations as much as possible

2020-09-07 18:12 UTC, axel1200 commented
ok but we can definitely not use the same code base

2020-09-07 19:35 UTC, Sheikah45 commented
Maybe not. Also do you think that we can't just make a card for local replays?

2020-09-07 19:35 UTC, Sheikah45 commented
I also meant more so in the style and naming conventions

2020-09-07 21:01 UTC, axel1200 commented
Have fun do what u like :D

2020-11-07 05:02 UTC, Sheikah45 commented
Fixes #1763

2020-11-07 14:58 UTC, axel1200 reviewed
Looks neat

2020-11-13 14:19 UTC, merged