Feature/#1814 pagination of mods final
FAForever/downlords-faf-client pull request #1831
Opened 2020-07-16 21:01 UTC by Aksiznarf-Uar

Created pagination for the mod vault.

2020-07-17 12:55 UTC, 1-alex98 requested changes
Unit tests failing

2020-07-17 12:55 UTC, axel1200 commented on src/main/java/com/faforever/client/mod/ModVaultController.java
> +    JavaFxUtil.assertBackgroundThread();
if this is really the background thread why load fxml on the background thread just above :thinking:

2020-07-17 12:55 UTC, axel1200 commented on src/main/java/com/faforever/client/mod/ModVaultController.java
> +    JavaFxUtil.assertBackgroundThread();
Also I guess make assert on method top

2020-07-23 12:57 UTC, 1-alex98 requested changes

2020-07-23 12:57 UTC, axel1200 commented on src/main/java/com/faforever/client/mod/ModVaultController.java
> +  public String requestedModType;
enum?

2020-07-23 12:57 UTC, axel1200 commented on src/main/java/com/faforever/client/mod/ModVaultController.java
> +    });
ident

2020-07-23 12:57 UTC, axel1200 commented on src/main/java/com/faforever/client/mod/ModVaultController.java
> +    loadingLabel.setVisible(true);
enterLoadingState()

2020-07-23 12:57 UTC, axel1200 commented on src/main/java/com/faforever/client/mod/ModVaultController.java
> +          appendSearchResult(mods, searchResultPane);
missleading name

2020-08-20 12:16 UTC, Sheikah45 commented
@axel1200 should this be closed?

2020-08-20 14:58 UTC, axel1200 commented
yes

2020-08-20 14:58 UTC, closed without merging