Add in check if game is running
FAForever/downlords-faf-client pull request #1905
Opened 2020-09-14 00:59 UTC by Sheikah45

Attempts to add in a check for if the game is running before closing the client currently an alert pops up but the window closes anyway

2020-09-14 01:02 UTC, Sheikah45 commented
@micheljung I am trying to add in the check for if FA is still running before closing the client however a closerequest event never gets sent so that event handler cannot be used. Currently it uses onHiding as the event to pick up on however there is no way to stop the window from being hidden. From looking at the code it might be best to implement something in the windowController or override its onCloseClicked method however the windowController is defined in your fxStage and wanted to know if you had any ideas and if we should implement our own windowFXML as there is an option to specify the fxml used.

2020-10-03 20:27 UTC, Sheikah45 commented
anything to do here?

2020-10-04 19:42 UTC, axel1200 requested changes

2020-10-04 19:42 UTC, axel1200 commented on src/main/java/com/faforever/client/FafClientApplication.java
> +                window.hide();
Platform.exit()

2020-10-04 19:54 UTC, axel1200 approved these changes

2020-10-04 19:54 UTC, axel1200 commented
Remember me if CI ran through

2020-10-04 19:58 UTC, Sheikah45 commented
CI passed

2020-10-04 21:22 UTC, merged