Use addImmediateErrorNotification
FAForever/downlords-faf-client pull request #1921
Opened 2020-09-18 02:12 UTC by Sheikah45

Fixes #1445 

Use addImmediateErrorNotification for all Error Notifications and add logging before.

2020-10-03 20:28 UTC, Sheikah45 commented
anything to do here?

2020-10-04 19:40 UTC, axel1200 approved these changes, later dismissed

2020-10-04 19:40 UTC, axel1200 commented
Yes rebase @Sheikah45

2020-10-15 21:28 UTC, Brutus5000 requested changes
I like it

2020-10-15 21:28 UTC, Brutus5000 commented on src/main/java/com/faforever/client/patch/GameUpdaterImpl.java
> +          log.warn("Game not terminated correctly", throwable);
*did

2020-10-15 21:28 UTC, Brutus5000 commented on src/main/java/com/faforever/client/game/GenerateMapController.java
>    }
All of these warning should either be moved outside the if block or customized to say more about the type of error.

2020-10-16 09:35 UTC, Brutus5000 approved these changes

2020-10-16 16:25 UTC, merged

2020-10-16 17:17 UTC, Katharsas commented
Nice