Bugfix/#2024 Filtering users in chat makes chat only users disappear forever
FAForever/downlords-faf-client pull request #2038
Opened 2020-11-15 02:56 UTC by ivan-gryzunov

Fixes #2024 

I wanted to add filter tests to avoid these errors in the future, but I have no idea how to do it.

2020-11-15 10:04 UTC, ivan-gryzunov commented
The PR is ready to review

2020-11-15 18:16 UTC, Brutus5000 requested changes
Nice catch.

2020-11-15 18:16 UTC, Brutus5000 commented on src/main/java/com/faforever/client/chat/UserFilterController.java
> +    if (countryFilterField.getText().isEmpty()) {
Add a comment that this addresses chat-only users for future reference.

2020-11-15 18:16 UTC, Brutus5000 commented on src/main/java/com/faforever/client/chat/UserFilterController.java
> +
remove empty line

2020-11-17 13:37 UTC, Brutus5000 approved these changes

2020-11-21 15:26 UTC, Sheikah45 approved these changes
looks good

2020-11-22 16:52 UTC, merged