Store faction selection in preferences
FAForever/downlords-faf-client pull request #2112
Opened 2021-01-09 11:51 UTC by BlackYps

Fixes #2087

2021-01-10 15:23 UTC, Sheikah45 requested changes

2021-01-10 15:23 UTC, Sheikah45 commented on src/test/java/com/faforever/client/teammatchmaking/TeamMatchmakingControllerTest.java
> +  private MatchmakerPrefs matchmakerPrefs;
Rather than mocking the preferences you can just use the preferencesBuilder to create one and pass that

2021-01-12 13:34 UTC, Sheikah45 requested changes
This doesn't currently work. The factions are preserved in the client UI however when I starting up the client never sends the preferred factions to the server so when joining a queue all factions are still valid choices

2021-01-12 15:15 UTC, Sheikah45 commented on src/test/java/com/faforever/client/teammatchmaking/TeamMatchmakingControllerTest.java
> +    when(preferencesService.getPreferences()).thenReturn(preferences);
duplicated line

2021-01-12 15:33 UTC, BlackYps commented
Oh, didn't see you reviewed already

2021-01-13 01:29 UTC, Sheikah45 approved these changes

2021-01-13 01:29 UTC, merged