Automatically update map when hosting a game
FAForever/downlords-faf-client pull request #2114
Opened 2021-01-14 03:36 UTC by ivan-gryzunov

Closes #1986

2021-01-14 03:53 UTC, ivan-gryzunov commented
Do I need to add unit tests? What do you think?

2021-01-14 04:05 UTC, Sheikah45 commented
Tests are always good. Helps to make sure that things don't get broken by future changes

2021-01-14 15:46 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/MapBean.java
> +
I would move this operation to the MapService as the MapBean is really just a data storage object

2021-01-14 15:48 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/MapBean.java
> +
Also the latestMapVersion should always be the most recent so you don't have to check the version specifically just check if the latest is the same as the one you are comparing to.

2021-01-14 15:59 UTC, ivan-gryzunov commented on src/main/java/com/faforever/client/map/MapBean.java
> +
Good! I did not think about it.

2021-01-16 00:24 UTC, Sheikah45 requested changes
Very thorough tests!
Looks good just a log statement in the ignored exception would be nice

2021-01-16 00:24 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/MapService.java
> +        } catch (CompareMapVersionException ignored) {  }
should at least add a log statement

2021-01-17 21:01 UTC, Sheikah45 approved these changes

2021-01-17 21:10 UTC, merged