Convert Chat Service to non-blocking kitteh irc
FAForever/downlords-faf-client pull request #2126
Opened 2021-01-23 05:30 UTC by Sheikah45

This changes the chat service implementation to use kitteh irc library which utilizes netty and is non-blocking. I have observed significant decreases in both cpu and gpu load with this implemented. This also allows us to move away from the modified pircbotx library

2021-01-23 05:35 UTC, Sheikah45 commented
This should also definitely close #1892

2021-01-23 18:19 UTC, Sheikah45 commented
Hmm it is lower at over time but am running into a high startup cost for some reason

2021-01-23 22:03 UTC, Brutus5000 requested changes

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/java/com/faforever/client/chat/ChatChannel.java
> +public class ChatChannel {
If everything is immutable consider making it a lombok `@Value` class

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/resources/i18n/messages.properties
> +chat.joinAChannel=Join a chatChannel
Derp all across this file xD

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/resources/i18n/messages_ru.properties
> +# i assume chatChannel == chat
derp

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/resources/theme/chat/channel_tab.fxml
> +                  styleClass="chat-chatChannel-users-pane" SplitPane.resizableWithParent="false" minWidth="300.0">
probably unintended

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/resources/theme/chat/private_chat_tab.fxml
> +     fx:controller="com.faforever.client.chat.PrivateChatTabController" styleClass="private-chatChannel-tab">
probably unintended

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/java/com/faforever/client/chat/TrustAllTrustManagerFactory.java
> +public class TrustAllTrustManagerFactory extends TrustManagerFactory {
TrustAllTrust? Weird name :D
Maybe TrustEverony or TrustUntrusted

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/java/com/faforever/client/chat/KittehChatService.java
> +        .flatMap(channel -> channel.getUserModes(user).stream().flatMap(Collection::stream))
Instead of double flatmap maybe split it into 2 lines

2021-01-23 22:03 UTC, Brutus5000 commented on src/main/java/com/faforever/client/chat/KittehChatService.java
> +        && sender.getPlayer().isPresent()
you can skip this check if you use .map(Player::getSocialStatus) on the optional and then `== Optional.of(SocialStatus.FOE)`

2021-01-23 22:05 UTC, Sheikah45 commented on src/main/resources/i18n/messages.properties
> +chat.joinAChannel=Join a chatChannel
ah missed the refactor by intellij

2021-02-05 14:22 UTC, Sheikah45 commented
Was able to fix the high startup. It was querying who for every channel on join and I just set the logic to do that to false.

2021-02-10 03:45 UTC, merged

2021-02-11 16:45 UTC, Katharsas commented
Nice!