#1966 - Highlight games with friends
FAForever/downlords-faf-client pull request #2264
Opened 2021-06-06 17:12 UTC by ivan-gryzunov

Closes #1966

2021-06-06 17:13 UTC, ivan-gryzunov commented
<details>
  <summary>Demo</summary>

![demo](https://user-images.githubusercontent.com/38242291/120933642-af9c0880-c703-11eb-8bf2-25bb2ddadb98.gif)


</details>

2021-06-08 10:38 UTC, Sheikah45 commented
Personally I am not really a fan of adding another check box to the top of the games table especially as it has a rather long name.

2021-06-08 15:03 UTC, ivan-gryzunov commented
@Sheikah45 Any ideas or suggestions?

2021-06-08 15:08 UTC, Sheikah45 commented
I wonder if just having it always been on as like a property of the game would be good or adding an icon that can just be displayed like the lock for private games

2021-06-08 16:14 UTC, ivan-gryzunov commented
@Sheikah45 Maybe simply to paint current/max players label to green color?

2021-06-08 16:17 UTC, ivan-gryzunov commented
I do not want to add the icons because the table is overloaded

2021-06-08 16:21 UTC, Sheikah45 commented
Maybe or the title. But I don't mind the background highlighting you already have. Although it may not be apparent what it means when people first see it

2021-06-09 20:28 UTC, 1-alex98 commented on src/main/resources/theme/style.css
> +  -fx-background-color: rgba(42, 253, 53, 0.15);
Define colour in colours.css

2021-06-13 12:06 UTC, ivan-gryzunov commented
> Maybe or the title. But I don't mind the background highlighting you already have. Although it may not be apparent what it means when people first see it

The title and number of players with green color looked unethical. So I decided to leave the background highlighting unchanged.

2021-06-17 03:58 UTC, Sheikah45 requested changes

2021-06-17 03:58 UTC, Sheikah45 commented on src/main/java/com/faforever/client/player/PlayerService.java
> +    synchronized (game.getTeams()) {
I would synchronize then get the teams

2021-06-17 03:58 UTC, Sheikah45 commented on src/main/java/com/faforever/client/player/PlayerService.java
> +  private List<String> getPlayersNamesOfAllTeams(Map<String, List<String>> teams) {
I would rename to getAllPlayerNames

2021-06-19 12:43 UTC, Sheikah45 requested changes
Small change on how coop games are detected

2021-06-19 12:43 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GamesTableController.java
> +                  && !coopMissionName.isVisible()); // do not highlight games in coop tab
```suggestion
                  && game.getGameType() != GameType.COOP
```

2021-06-19 13:16 UTC, Sheikah45 commented
Went ahead and changed it myself

2021-06-19 13:24 UTC, Sheikah45 approved these changes

2021-06-19 13:25 UTC, merged