Support emojis
FAForever/downlords-faf-client pull request #2430
Opened 2021-11-29 20:48 UTC by ivan-gryzunov

Closes #436

<details> 
  <summary>Demo</summary>
   
![demo](https://user-images.githubusercontent.com/38242291/143940743-7a97c358-8fc4-4791-ba0d-6d7fcd5a2bb2.gif)

</details>

2021-11-29 20:48 UTC, ivan-gryzunov commented
Please note that the PR is still not in its final stages.
I need some feedback. Depending on the feedback, I will continue to work with this or close it.

2021-11-29 20:54 UTC, Sheikah45 commented
What are you looking for feedback on specifically?

2021-11-29 20:59 UTC, ivan-gryzunov commented
Anything. UI, implementation, code complexity....

2021-11-29 21:10 UTC, Sheikah45 commented
Gotcha will take a look later today

2021-11-29 23:24 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/ChatUserService.java
> +          TypeFactory.defaultInstance().constructCollectionType(List.class, EmoticonsGroup.class));
We don't want to create a new ObjectMapper every time as they are expensive to create. We have an ObjectMapper that is created on application start and can be injected by adding it to the constructor through spring

2021-11-29 23:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/ChatUserService.java
> +          TypeFactory.defaultInstance().constructCollectionType(List.class, EmoticonsGroup.class));
I also would just make a class that is a list of emoticons rather than using the type factory to deserialize

2021-11-29 23:30 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/ChatUserService.java
> +        emoticonShortcodes.put(shortcode, emoticon.getSvgFilePath());
No need to collect to a list here if we are just going to iterate through it again. Just use forEach

2021-11-29 23:41 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/ChatUserService.java
> +  private static final ClassPathResource EMOTICONS_JSON_FILE_RESOURCE = new ClassPathResource("images/emoticons/emoticons.json");
It would be better to create an EmoticonService rather than embed it in this one as they don't have much to do with each other

2021-11-29 23:48 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/ChatUserService.java
> +      emoticonsGroups = Collections.emptyList();
Probably want some user notification here otherwise it will just go unnoticed

2021-11-29 23:53 UTC, Sheikah45 reviewed
Looks decent to me so far. I think we would want to create a separate EmoticonService rather than coopt the ChatUserService as that is not really its purpose.

Additionally will have to dig in a little more to the cost benefits of having the svgs as separate files vs having them in css

2021-11-30 10:29 UTC, ivan-gryzunov commented
> Additionally will have to dig in a little more to the cost benefits of having the svgs as separate files vs having them in CSS

I'm not sure, but ... What to do with complex paths? How to combine them and put them in the `-fx-shape` attribute. I didn't find any information on Google.

2021-11-30 10:36 UTC, Sheikah45 commented
What do you mean by complex paths?

2021-11-30 10:38 UTC, ivan-gryzunov commented
For example, content of `1f601.svg`:

![image](https://user-images.githubusercontent.com/38242291/144031975-bfa01dc1-1fe2-49a5-be54-b2cf2ac1237d.png)

2021-11-30 13:01 UTC, ivan-gryzunov commented
Found another way not to use separate SVG files.

2021-11-30 15:06 UTC, Sheikah45 commented
Ah yeah that is much better

2021-12-04 03:29 UTC, Sheikah45 requested changes

2021-12-04 03:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/AbstractChatTabController.java
> +    EMOTICON_SHORTCODE_DETECTOR_PATTERN = emoticonService.getEmoticonShortcodeDetectorPattern();
This is only used in one place so I would just inline the get call. Right now it's definition as a constant like this doesn't really match. If we keep it as a property I would jsut use normal naming convention but since it is part of the emoticonService I don't see a reason to have it in this class as well.

2021-12-04 03:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/AbstractChatTabController.java
> +  }
This getter is unnecessary nothing uses it and I don't think we want to expose this button anyway outside of as necessary for the fxml

2021-12-04 03:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/AbstractChatTabController.java
> +    Bounds screenBounds = emoticonsButton.localToScreen(emoticonsButton.getBoundsInLocal());
The getter here is unnecessary

2021-12-04 03:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/emoticons/EmoticonService.java
> +    initializePattern();
I would move initializePattern into loadAndVerifyEmoticons so that way whenever emoticons are loaded the pattern is up to date

2021-12-04 03:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/emoticons/EmoticonsWindowController.java
> +      textInputControl.appendText(" ".concat(shortcode).concat(" "));
```suggestion
      textInputControl.appendText(" " + shortcode + " ");
```

2021-12-04 03:29 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/emoticons/EmoticonsWindowController.java
> +  public void associateWith(TextInputControl textInputControl) {
Just use @Setter on the TextinputControl field
```suggestion
  public void setTextControl(TextInputControl textInputControl) {
```

2021-12-04 03:32 UTC, Sheikah45 commented
It would also be good to add documentation somewhere on how to add emojis

2021-12-04 18:23 UTC, ivan-gryzunov commented
Ok. I need time to write the documentation. Where to place it? Wiki?

2021-12-04 18:30 UTC, Sheikah45 commented
Yes that would be best

2021-12-04 18:32 UTC, Sheikah45 commented
https://github.com/FAForever/downlords-faf-client/wiki/Adding-Emojis

2021-12-04 18:39 UTC, Sheikah45 approved these changes

2021-12-05 15:28 UTC, merged