Show a map preview in close up
FAForever/downlords-faf-client pull request #2599
Opened 2022-03-02 20:07 UTC by Marc-Spector

Closes #2595 

<details>

<summary>Demo</summary>

![demo3](https://user-images.githubusercontent.com/38242291/156440894-29827005-594f-4241-9d66-682c2e17314d.gif)

</details>

2022-03-02 20:58 UTC, Sheikah45 commented
I would use the dialogLayout rather than a raw stage to keep the formatting the same

2022-03-03 08:04 UTC, Marc-Spector commented
The dialog has a big minus - you need to specify a parent with the `StackPane` class. I used the popup instead of the dialog. It seems to be the best option.

2022-03-03 12:31 UTC, Sheikah45 requested changes

2022-03-03 12:31 UTC, Sheikah45 commented on src/main/java/com/faforever/client/replay/ReplayDetailController.java
> +        .ifPresent(map -> mapService.showMapInCloseUp(map.getFolderName())));
Make this into a function and set the onMouseClicked in the fxml

2022-03-03 12:31 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/MapService.java
> +  }
I agree that this should be moved to some other util service and made general. The Services should not be creating UI elements.

Ideally the mapService would load the image and then a util class would be called that creates the popup all from the Controller Class that has the click function.

2022-03-03 12:31 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/MapDetailController.java
> +        .ifPresent(map -> mapService.showMapInCloseUp(map.getFolderName())));
Make this a function and set the onMouseClicked in the fxml

2022-03-03 12:31 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GameDetailController.java
> +        Optional.ofNullable(game.get()).ifPresent(gameBean -> mapService.showMapInCloseUp(gameBean.getMapFolderName())));
Make this a function and set the onMouseClicked in the fxml

2022-03-04 00:01 UTC, Sheikah45 requested changes

2022-03-04 00:01 UTC, Sheikah45 commented on src/main/java/com/faforever/client/util/PopupUtil.java
> +  public static void showImageInCloseUp(Image image) {
```suggestion
  public static void showImagePopup(Image image) {
```

2022-03-04 00:01 UTC, Sheikah45 commented on src/main/java/com/faforever/client/util/PopupUtil.java
> +  public static void showImageInCloseUp(Image image, double imageHeightInPercentage) {
```suggestion
  public static void showImagePopup(Image image, double imageHeightInPercentage) {
```

2022-03-10 23:20 UTC, Sheikah45 approved these changes

2022-03-10 23:21 UTC, merged