WIP: Mute/unmute the user
FAForever/downlords-faf-client pull request #2709
Opened 2022-05-19 01:01 UTC by Marc-Spector

Closes #2214 

The icons has more interactive
![demo55111](https://user-images.githubusercontent.com/38242291/169180042-29da7c23-b961-4158-9f5f-b9701665a6cf.gif)

2022-05-19 01:18 UTC, Marc-Spector commented
Replaced mute icon with blocked eye icon 
![image](https://user-images.githubusercontent.com/38242291/169181661-2deb950a-e23e-4baa-970e-2e59f7ecb629.png)

2022-05-30 11:02 UTC, Sheikah45 requested changes
At the moment I think the behavior as is, is a little misleading. Right now you can only mute and un-mute the user from a private chat window. However when muted they also have their messages hidden in all other channels but this is not clear from the UI.

Additionally there is no way to know in total which users you have muted. You would have to individually go through each user to see if you had them muted or not. I think it would be good to have a separate property like isModerator so we can properly display who is muted.

Additionally right now this is only capable of muting players since we use ids, however a large impetus behind this feature was the ability to also mute chat only users so we should primarily use ids but have a fallback of nicks to check as well, otherwise this is just entirely parallel to the foe option.

2022-05-30 11:02 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/ChatService.java
> +  ObservableSet<Integer> getMutedUserIds();
The muted should not only be userIds as chat only users will not have consistent ids associated with them

2022-05-30 11:02 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/KittehChatService.java
> +    return getOrCreateChatUser(username, username, false).getPlayer().map(AbstractEntityBean::getId).orElse(null);
This creates a lot of chatUsers that might not actually exist. If all we want is the id then we should just use the playerService directly to get the player rather than unecessarily creating a chatUser. Especially since this is called for every user's message through isUserMuted so it will think we have a private channel open with every user who sends a message and also won't have a chance to be closed.

2022-05-30 11:02 UTC, Sheikah45 commented on src/main/java/com/faforever/client/chat/KittehChatService.java
> +        && preferencesService.getPreferences().getChat().getHideFoeMessages() || isUserMuted(username)) {
For clarity I would group the first two conditions with parentheses

2022-10-04 12:50 UTC, Marc-Spector commented
I closing the PR. I think it's better to wait for new fields to appear in the DB. https://github.com/FAForever/downlords-faf-client/issues/2214#issuecomment-1027266196

2022-10-04 12:50 UTC, closed without merging