#3118 add map vault search prefs
FAForever/downlords-faf-client pull request #3185
Opened 2024-05-28 14:29 UTC by obydog002

https://github.com/FAForever/downlords-faf-client/issues/3118

Add persistent settings for all the options in the map vault search page

2024-05-28 23:12 UTC, Sheikah45 requested changes

2024-05-28 23:12 UTC, Sheikah45 commented on src/main/java/com/faforever/client/preferences/MapSearchPrefs.java
Can the formatting in this file be fixed?

2024-05-29 00:55 UTC, obydog002 commented on src/main/java/com/faforever/client/preferences/MapSearchPrefs.java
tabs :)

2024-05-31 21:27 UTC, Sheikah45 approved these changes

2024-05-31 21:27 UTC, merged