Change generator UI for the new map generator version
FAForever/downlords-faf-client pull request #3187
Opened 2024-05-29 22:17 UTC by BlackYps

![grafik](https://github.com/FAForever/downlords-faf-client/assets/52536103/303f16f1-d55c-4f47-b4b5-ccf0c85b18fe)

2024-05-29 22:36 UTC, Sheikah45 requested changes

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GenerateMapController.java
> +  protected void setTextureGenerators(List<String> textureGenerators) {
TextureStyles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GenerateMapController.java
> +  protected void setResourceGenerators(List<String> resourceGenerators) {
ResourceStyles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GenerateMapController.java
> +  protected void setPropGenerators(List<String> propGenerators) {
PropStyles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GenerateMapController.java
> +  protected void setTerrainGenerators(List<String> terrainGenerators) {
TerrainStyles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/generator/GeneratorCommand.java
> +    String propGenerator,
styles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/map/generator/GeneratorOptions.java
> +    String propGenerator,
styles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/preferences/GeneratorPrefs.java
> +  private final StringProperty propGenerator = new SimpleStringProperty("");
styles

2024-05-29 22:36 UTC, Sheikah45 commented on src/main/java/com/faforever/client/game/GenerateMapController.java
> +    }
This can set the mapstyle and custom style options which is an error in the generator

2024-06-01 12:14 UTC, BlackYps commented
Do you have an idea why there is excessive space between the heading and the spawn number spinner? It's not because of the hidden command line field, because even if I enable that, there is still too much space under the heading.

2024-06-01 15:08 UTC, Sheikah45 commented
I never was exactly sure, something with the gridpane I think

2024-06-01 20:06 UTC, BlackYps commented
There is a weird interaction going on. When the heading text is the longest of all elements in the column, then it needs significantly more vertical space. This can easily be observed by shortening the text. I have no idea why this happens though

2024-06-15 02:13 UTC, merged