finishes #767 copy username in chat
FAForever/downlords-faf-client pull request #769
Opened 2018-02-23 22:47 UTC by Geosearchef

![capture](https://user-images.githubusercontent.com/5748922/36620547-e5700612-18f3-11e8-8418-3872b2136f41.PNG)

2018-02-24 08:19 UTC, Brutus5000 submitted a review, later dismissed

2018-02-24 12:45 UTC, micheljung requested changes

2018-02-24 12:45 UTC, micheljung commented on src/main/resources/i18n/messages_de_DE.properties
> +chat.userContext.copyUsername=Nutzernamen kopieren
`Benutzername kopieren`

2018-02-24 12:48 UTC, micheljung commented
Please change the commit message to use `Fixes #767`, "finishes" [is not a valid keyword](https://help.github.com/articles/closing-issues-using-keywords/)

2018-02-24 14:38 UTC, Geosearchef commented
encoding/text fixed, didn't care about the keyword as it diddn't work last time I tried to use one on this repo.

2018-03-24 11:52 UTC, 1-alex98 requested changes
Change encoding in seperate PR and rename commit messages

2018-03-26 19:56 UTC, Geosearchef commented
done

2018-03-28 15:52 UTC, micheljung approved these changes

2018-03-28 15:52 UTC, merged

2018-03-28 17:39 UTC, micheljung commented on src/main/java/com/faforever/client/chat/ChatUserContextMenuController.java
> +  }
After merging I realized, it'd be nice if there was a unit test for this.