Feature/#26 tournaments tab
FAForever/downlords-faf-client pull request #926
Opened 2018-06-01 22:16 UTC by Brutus5000

The return of the tournaments tab. Featuring our api-challonge-proxy.

2018-06-03 18:57 UTC, 1-alex98 submitted a review, later dismissed
Top

2018-06-03 18:57 UTC, axel1200 commented on src/main/java/com/faforever/client/remote/FafService.java
> +  public CompletableFuture<List<TournamentBean>> getAllTournaments() {
@Async

2018-06-03 21:53 UTC, Brutus5000 commented on src/main/java/com/faforever/client/remote/FafService.java
> +  public CompletableFuture<List<TournamentBean>> getAllTournaments() {
Done 👍

2018-06-11 21:51 UTC, micheljung submitted a review, later dismissed

2018-06-11 21:51 UTC, micheljung commented on src/main/java/com/faforever/client/tournament/TournamentsController.java
> +      startingDate = MessageFormat.format("{0} {1}", timeService.asDate(tournamentBean.getStartingAt()), timeService.asShortTime(tournamentBean.getStartingAt()));
this (and below) should also be an internationalized string. So it can either be `{0} at {1}` or `{0} um {1}` etc.

2018-06-11 21:51 UTC, micheljung commented on src/main/java/com/faforever/client/tournament/TournamentsController.java
> +      throw new RuntimeException(e);
Please use @Sneakythrows instead

2018-06-11 21:51 UTC, micheljung commented on src/main/resources/i18n/messages.properties
> +dateTime={0,date} {0,time}
This is unused

2018-06-12 06:39 UTC, Brutus5000 commented
I have just retestet it and wondered why it is broken. Adding the @Async annotation breaks it without any exception in the log. Any ideas? @axel1200  @micheljung

2018-06-12 20:17 UTC, axel1200 commented on src/main/java/com/faforever/client/tournament/TournamentsController.java
> +        });
Hier .exceptionall

2018-06-12 20:50 UTC, 1-alex98 requested changes

2018-06-12 20:50 UTC, axel1200 commented on src/main/java/com/faforever/client/tournament/TournamentsController.java
> +      log.error(throwable.getLocalizedMessage());
Log the whole exception with the stacktrace etc.

2018-06-13 07:51 UTC, micheljung commented
@Brutus5000 Any more details about the "breaks it" part?

2018-06-13 21:56 UTC, Brutus5000 commented
It was a white page without exception, but thanks to axel I was able to solve it.

2018-06-14 21:37 UTC, merged