Rework/Fix game tiles
FAForever/downlords-faf-client pull request #954
Opened 2018-08-04 20:09 UTC by axel1200

Fixes #945

2018-11-24 15:14 UTC, micheljung requested changes

2018-11-24 15:14 UTC, micheljung commented on src/main/java/com/faforever/client/game/GameService.java
> +  }
Actually, any access on `uidToGameInfoBean` *must* be synchronized. Otherwise, you run into race conditions. Therefore, exposing this is dangerous and should be avoided.

Also, there are no spaces in front of commas but periods at the end of JavaDoc ;-)

If you need to expose it, you could return an immutable copy. If it's needed to e.g. add listeners to it, a method can be provided that adds listeners.

2018-11-24 15:14 UTC, micheljung commented on src/main/java/com/faforever/client/game/GamesTableController.java
> +    passwordChangeListener = (observable, oldValue, newValue) -> passwordProtectionColumn.setVisible(newValue);
`modChangedListener` sounds like a mod has been changed. Better: `showModdedGamesChangedListener`.
And `showPasswordProtectedGamesChangedListener`

2018-12-01 23:47 UTC, axel1200 commented on src/main/java/com/faforever/client/game/GameService.java
> +  }
I exposed it to use it as a monitor

2019-04-26 17:20 UTC, axel1200 commented
@Geosearchef would you review

2019-05-02 19:15 UTC, micheljung commented on src/main/java/com/faforever/client/game/GameService.java
> +  }
Please check if there's a better way, this violates the Law of Demeter

2019-05-02 19:17 UTC, micheljung requested changes

2019-05-02 19:17 UTC, micheljung commented on src/main/java/com/faforever/client/game/GamesTilesContainerController.java
> +              log.error("Tried to remove game tile that did not exist.");
Warn, not error

2019-05-03 22:01 UTC, merged