Java ice adapter
FAForever/downlords-faf-client pull request #988
Opened 2018-10-11 09:16 UTC by Geosearchef

2018-10-11 19:39 UTC, axel1200 commented
What exactly do you want us to do here?

2018-10-11 21:39 UTC, Geosearchef commented
Take a look at the changes, they are WIP

2018-10-12 13:19 UTC, 1-alex98 requested changes

2018-10-12 13:19 UTC, axel1200 commented on build.gradle
> +  src "https://geosearchef.de/faf-ice-adapter.jar"
I know you know but we need to change before merge

2018-10-12 13:19 UTC, axel1200 commented on src/main/java/com/faforever/client/fa/relay/ice/IceAdapterImpl.java
> +//    return iceServers.stream()
Remove comments

2018-10-12 13:19 UTC, axel1200 commented on src/main/java/com/faforever/client/fa/relay/ice/IceAdapterImpl.java
> +//    if (iceServer.getCredential() != null) {
Remove

2018-10-12 13:19 UTC, axel1200 commented on src/main/java/com/faforever/client/fa/relay/ice/IceAdapterImpl.java
> +      map.put("username", iceServers.get(2).getUsername());
Why get(2)

2018-10-12 13:19 UTC, axel1200 commented on src/main/resources/application-prod.yml
> +    host: irc.test.faforever.com
Remove test...

2018-10-12 13:19 UTC, axel1200 commented on src/main/resources/application-prod.yml
> +    base-url: http://api.faf.micheljung.ch:10080
Reset

2019-04-17 15:03 UTC, closed without merging